# Generated by Django 4.2.27 on 2025-12-18 10:40

from django.db import migrations, models
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('warehouse_city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=6)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='is_refurnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='media/products/', validators=[products.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='products',
            name='sku',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
