# Generated by Django 4.2.27 on 2025-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_warehouse_products_is_refurnished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('EUR', 'EUR'), ('CAD', 'CAD')], max_length=3),
        ),
    ]
