# Generated by Django 4.2.27 on 2025-12-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_currency_alter_products_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.warehouse'),
        ),
    ]
