# Generated by Django 4.2.27 on 2025-12-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='products',
            name='warehouse',
            field=models.ManyToManyField(to='products.warehouse'),
        ),
    ]
